create table meu_ecommerce
(id_produto number GENERATED BY DEFAULT AS IDENTITY --Esta função gera o ID automático a cada linha inserida
,descricao varchar2(150)
,valor_venda number
,novo_usado varchar2(5)
,qtde_estoque number
,pais_origem varchar2(50)
,descricao_longa varchar2(2000)
,data_compra date --data que comprei esse item
);

-- Inserir dados fictícios na tabela "meu_ecommerce" (cada linha individualmente)
INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Smartphone Modelo X', 599.99, 'Novo', 1, 'EUA', 'Um smartphone de última geração com recursos incríveis.', TO_DATE('2023-01-15', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Notebook Ultra Pro', 1299.99, 'Novo', 1, 'China', 'Um notebook de alta performance para tarefas intensivas.', TO_DATE('2022-12-10', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Fones de Ouvido Sem Fio', 89.99, 'Novo', 1, 'Coreia do Sul', 'Fones de ouvido com qualidade de som excepcional.', TO_DATE('2023-02-20', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Câmera DSLR Profissional', 1499.99, 'Usado', 1, 'Japão', 'Uma câmera DSLR usada, mas em excelente estado.', TO_DATE('2022-11-05', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Televisão 4K Ultra HD', 799.99, 'Novo', 1, 'Taiwan', 'Uma TV com resolução incrível para uma experiência imersiva.', TO_DATE('2023-03-08', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Tablet Premium', 299.99, 'Novo', 1, 'Alemanha', 'Um tablet de alta qualidade com tela HD.', TO_DATE('2023-04-12', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Monitor Ultra Wide', 399.99, 'Novo', 1, 'Coréia do Sul', 'Um monitor de alta resolução para produtividade.', TO_DATE('2023-05-03', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Cadeira Gamer', 149.99, 'Novo', 1, 'Brasil', 'Uma cadeira ergonômica para jogadores.', TO_DATE('2023-06-18', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Console de Videogame', 499.99, 'Novo', 1, 'Japão', 'Um console de última geração para jogos.', TO_DATE('2023-07-02', 'YYYY-MM-DD'));

INSERT INTO meu_ecommerce (descricao, valor_venda, novo_usado, qtde_estoque, pais_origem, descricao_longa, data_compra)
VALUES ('Impressora Multifuncional', 89.99, 'Novo', 1, 'China', 'Uma impressora com recursos avançados.', TO_DATE('2023-08-27', 'YYYY-MM-DD'));

    
update meu_ecommerce
   set valor_venda = 500
 where id_produto = 1;   

delete meu_ecommerce
where id_produto = 5;

select * from meu_ecommerce
where valor_venda > 100;

select * from meu_ecommerce
where valor_venda < 100 ;   

select sum(valor_venda) 
  from meu_ecommerce;    
    
select round(avg(valor_venda),2) 
  from meu_ecommerce;    

select max(valor_venda) 
  from meu_ecommerce ;

select * from  meu_ecommerce
    where valor_venda = 1499.99;

select min(valor_venda) 
  from meu_ecommerce ;

select * from  meu_ecommerce
    where valor_venda = 89.99  ;

select pais_origem, count(*), sum(valor_venda) , avg(valor_venda)
    from meu_ecommerce
  group by pais_origem  ;
    
    
